name: Birthday Mailer

on:
  schedule:
    - cron: '0 5 * * *'  # Runs daily at 5:00 AM UTC (10:30 AM IST)

jobs:
  send-birthday-emails:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install Dependencies
        run: pip install -r requirements.txt

      - name: Run Birthday Script
        run: python birthday_mailer.py
        env:
          EMAIL: ${{ secrets.EMAIL }}
          EMAIL_PASSWORD: ${{ secrets.EMAIL_PASSWORD }}